name: my_sage_agent
description: "Agent Agent Digital Banking Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  keyboard_actions: ^4.2.1
  flutter_svg: ^2.2.3
  equatable: ^2.0.7
  logger: ^2.6.2
  flutter_bloc: ^9.1.1
  http: ^1.6.0
  device_info_plus: ^12.3.0
  geolocator: ^14.0.2
  package_info_plus: ^8.3.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  local_auth: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  string_validator: ^1.2.0
  shimmer: ^3.0.0
  file_picker: ^10.3.7
  uuid: ^4.5.2
  encrypt: ^5.0.3
  cryptography: ^2.9.0
  pointycastle: ^3.9.1
  xml: ^6.6.1
  convert: ^3.1.2
  flutter_udid: ^4.1.1
  sliver_tools: ^0.2.12
  persistent_bottom_nav_bar_v2: ^6.2.0
  go_router: ^16.3.0
  animate_do: ^4.2.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  flutter_native_contact_picker: ^0.0.11
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1
  envied: ^1.3.2
  freerasp: ^7.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  fluttertoast: ^9.0.0
  easy_refresh: ^3.4.0
  flutter_libphonenumber: ^2.7.0
  image_picker: ^1.2.1
  camera: ^0.11.3
  image: ^4.6.0
  google_mlkit_face_detection: ^0.13.1
  app_settings: ^7.0.0
  flutter_slidable: ^4.0.3
  google_fonts: ^7.0.0
  collection: ^1.19.1
  just_the_tooltip: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^1.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
  - assets/img/
  - assets/certificate.pem
